/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
    remotePatterns: [
      // Repo previews generated by GitHub for projects pulled from the API.
      { protocol: "https", hostname: "opengraph.githubassets.com" },
    ],
  },
}

export default nextConfig
